# Generated by Django 5.1.2 on 2024-10-09 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('position_level', models.CharField(choices=[('Junior', 'Junior'), ('Associate', 'Associate'), ('Mid senior', 'Mid senior'), ('Senior', 'Senior')], default='Junior', max_length=10)),
                ('company_name', models.CharField(max_length=255)),
                ('date_applied', models.DateField()),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected')], default='Applied', max_length=9)),
                ('applied_method', models.CharField(choices=[('Website', 'Website'), ('Job board', 'Job board'), ('Referral', 'Referral'), ('Email', 'Email')], default='website', max_length=9)),
                ('location', models.CharField(max_length=255)),
                ('job_link', models.URLField(blank=True, max_length=300, null=True)),
                ('recruiter_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('follow_up_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
