# Generated by Django 5.1.2 on 2024-10-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applyhub', '0002_profileimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
