# Generated by Django 5.1.2 on 2024-10-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyhub', '0003_delete_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
